### ISSUE TITLE
Fail to run exe

### ISSUE THREAD

**Issue by jinshuguangze** [chenhonghua/Feature-line-extraction#2]
According to your program, and can not input parameters, it shows parameter input error.
![_F)8S3PSXU}5B(JBO{8 R A](https://user-images.githubusercontent.com/22865420/159625062-c3b393c7-4895-4329-94e2-06a552d757c1.png)

**Comment by hhchenHKCLR** [comment]
Please follow the instruction letter "Readme.pdf", and ensure every step is the same.

**Comment by chenhonghua** [comment]
Please follow the instruction letter "Readme.pdf", and ensure every step is the same.

**Comment by jinshuguangze** [comment]
Every Step is same, even I tried the fandisk in data folder,but it also said "Please enter the correct para".

**Comment by chenhonghua** [comment]
I have checked it. The main reason is that the file path cannot contain any space. 
For example,  you should change D:\framework\point cloud\... as D:\framework\point-cloud\...
